<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

/**
 * Migration for users table.
 * 
 * Generated by AutoGen Migration Package
 * Connection: mysql
 * Driver: mysql
 * 
 * Original table structure from MySQL database:
 * - Engine: InnoDB
 * - Charset: utf8mb4
 * - Collation: utf8mb4_unicode_ci
 * - Auto Increment: 1
 */
return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('users', function (Blueprint $table) {
            // Primary key
            $table->bigIncrements('id');
            
            // User information
            $table->string('name', 255)->comment('User full name');
            $table->string('email', 255)->unique()->comment('User email address');
            $table->timestamp('email_verified_at')->nullable()->comment('Email verification timestamp');
            $table->string('password', 255)->comment('Hashed password');
            $table->rememberToken()->comment('Remember me token');
            
            // Profile information
            $table->string('first_name', 100)->nullable();
            $table->string('last_name', 100)->nullable();
            $table->string('phone', 20)->nullable();
            $table->date('birth_date')->nullable();
            $table->enum('status', ['active', 'inactive', 'suspended'])->default('active');
            
            // Settings and preferences
            $table->json('preferences')->nullable()->comment('User preferences as JSON');
            $table->string('timezone', 50)->default('UTC');
            $table->string('locale', 10)->default('en');
            
            // Social login
            $table->string('google_id', 255)->nullable();
            $table->string('facebook_id', 255)->nullable();
            $table->string('avatar_url', 500)->nullable();
            
            // Account tracking
            $table->timestamp('last_login_at')->nullable();
            $table->ipAddress('last_login_ip')->nullable();
            $table->unsignedTinyInteger('login_attempts')->default(0);
            $table->timestamp('locked_until')->nullable();
            
            // Timestamps
            $table->timestamps();
            $table->softDeletes();
            
            // Indexes
            $table->index('status');
            $table->index('created_at');
            $table->index(['status', 'created_at']);
            $table->index('last_login_at');
            $table->unique(['email', 'deleted_at']);
            
            // Table options
            $table->engine = 'InnoDB';
            $table->charset = 'utf8mb4';
            $table->collation = 'utf8mb4_unicode_ci';
            $table->comment('User accounts and profile information');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('users');
    }
};