<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Migration for posts table.
 * 
 * Generated by AutoGen Migration Package
 * Connection: mysql
 * Driver: mysql
 * 
 * Foreign key dependencies: users
 */
return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('posts', function (Blueprint $table) {
            // Primary key
            $table->bigIncrements('id');
            
            // Foreign key relationships
            $table->unsignedBigInteger('user_id')->comment('Author of the post');
            $table->unsignedBigInteger('category_id')->nullable()->comment('Post category');
            
            // Content fields
            $table->string('title', 255)->comment('Post title');
            $table->string('slug', 255)->unique()->comment('URL-friendly version of title');
            $table->text('excerpt')->nullable()->comment('Short description or summary');
            $table->longText('content')->comment('Full post content');
            
            // Metadata
            $table->enum('status', ['draft', 'published', 'archived'])->default('draft');
            $table->enum('visibility', ['public', 'private', 'protected'])->default('public');
            $table->string('featured_image', 500)->nullable();
            $table->json('meta_data')->nullable()->comment('Additional metadata as JSON');
            
            // SEO fields
            $table->string('meta_title', 255)->nullable();
            $table->text('meta_description')->nullable();
            $table->json('meta_keywords')->nullable();
            
            // Engagement tracking
            $table->unsignedInteger('view_count')->default(0);
            $table->unsignedInteger('like_count')->default(0);
            $table->unsignedInteger('comment_count')->default(0);
            $table->unsignedInteger('share_count')->default(0);
            
            // Publishing
            $table->timestamp('published_at')->nullable();
            $table->timestamp('featured_until')->nullable();
            $table->boolean('allow_comments')->default(true);
            $table->boolean('is_featured')->default(false);
            
            // Timestamps
            $table->timestamps();
            $table->softDeletes();
            
            // Indexes for performance
            $table->index('user_id');
            $table->index('category_id');
            $table->index('status');
            $table->index('visibility');
            $table->index('published_at');
            $table->index('is_featured');
            $table->index(['status', 'published_at']);
            $table->index(['user_id', 'status']);
            $table->index(['category_id', 'status']);
            
            // Full-text search index (MySQL specific)
            $table->fullText(['title', 'content']);
            
            // Foreign key constraints
            $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');
            $table->foreign('category_id')->references('id')->on('categories')->onDelete('set null');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('posts');
    }
};